timeout: 60sec
central:
  reports:
    datastores:
      - artifact://k1LoW/calver
      - artifact://k1LoW/colr
      - artifact://k1LoW/concgroup
      - artifact://k1LoW/curlreq
      - artifact://k1LoW/expand
      - artifact://k1LoW/filt
      - artifact://k1LoW/ghfs
      - artifact://k1LoW/ghput
      - artifact://k1LoW/gh-grep
      - artifact://k1LoW/gh-setup
      - artifact://k1LoW/github-script-ruby
      - artifact://k1LoW/gostyle
      - artifact://k1LoW/grpcstub
      - artifact://k1LoW/grpcurlreq
      - artifact://k1LoW/httpstub
      - artifact://k1LoW/ndiag
      - artifact://k1LoW/octocov
      - artifact://k1LoW/octocov-cachegrind
      - artifact://k1LoW/octocov-go-test-bench
      - artifact://k1LoW/octocov-runn-coverage
      - artifact://k1LoW/octoslack
      - artifact://k1LoW/repin
      - artifact://k1LoW/runn
      - artifact://k1LoW/sheer-heart-attack
      - artifact://k1LoW/single
      - artifact://k1LoW/smtptest
      - artifact://k1LoW/smtpurl
      - artifact://k1LoW/sqlc-go-one-or-fail
      - artifact://k1LoW/sshc
      - artifact://k1LoW/stopw
      - artifact://k1LoW/tbls
      - artifact://k1LoW/tcpdp
      - artifact://k1LoW/trivy-db-to
      - artifact://2manymws/keyrwmutex
      - artifact://2manymws/rc
      - artifact://2manymws/rcutil
      - artifact://2manymws/rl
      - artifact://2manymws/rp
      - artifact://2manymws/mm
  badges:
    datastores:
      - local://badges
  push:
    enable: true
  reReport:
    datastores:
      - mackerel://octocov
